name: CodeSniffer
author: discoverygarden
description: Runs static analysis on your PHP code.

inputs:
  path:
    description: The path (or paths) to run the analysis on.
    required: false
    default: ./
  extensions:
    description: Comma separated list of file extensions to test.
    required: false
    default: php,module,inc,install,test,profile,theme,css,info,md,yml
  suffix:
    description: Comma separated list of file extensions to test used by phpcs.
    required: false
    default: .php,*.module,*.inc,*.install,*.test,*.profile,*.theme,*.js,*.css,*.info
  lint:
    description: Comma separated list of file extentions to lint.
    required: false
    default: php,module,inc,install,test

runs:
  using: "composite"
  steps:
    - env:
        ACTION_PATH: ${{ inputs.path }}
        ACTION_EXTENSIONS: ${{ inputs.extensions }}
        ACTION_SUFFIX: ${{ inputs.suffix }}
        ACTION_LINT: ${{ inputs.lint  }}
      run: ${{ github.action_path }}/lint.sh
      shell: bash

branding:
  icon: 'check-square'
  color: 'blue'
